# RENAME FILE TO 'config.yml'
bot:
  token: MTIxNTA1OTM2NDA4NDQ1MzQ5Ng.GNDN1P.iTyrps_qvn3LB5x-QutNAj7cOy4B7KQjywIrWg
  owner_ids:
    - 123456789123456789
    - 987654321987654321
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
