# RENAME FILE TO 'config.yml'
bot:
  token: MTIxNjczNjEzODc4NjUwNDczNA.Ge-7fr.O6BEpCU5hxdwDL3426J8sajMOQvL0adQ-5cLw0
  owner_ids:
    - 123456789123456789
    - 987654321987654321
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
